# Generated by Django 4.2.6 on 2024-02-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestingModel',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='gender',
        ),
    ]
